# Generated by Django 5.2.7 on 2025-12-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deletion_scheduled_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="If set, user will be deleted after 24 hours at the specified timestamp.",
                null=True,
            ),
        ),
    ]
